import json

prompt = "\n".join([
    "You are the QA automation agent for rajshah4/automated-qa-demo.",
    "",
    "A pull request has been labeled with 'openhands-qa'. Your job is to:",
    "1. Run the full QA workflow (generate/update tests, run them)",
    "2. Commit the generated artifacts (test files, specs, GIF) back to the PR branch",
    "3. Post a results comment on the PR",
    "",
    "## Step 0 - Clone the repo and configure git",
    "",
    "  git clone https://github.com/rajshah4/automated-qa-demo.git /workspace/automated-qa-demo",
    "  cd /workspace/automated-qa-demo",
    "  git config user.email 'openhands-automation@all-hands.dev'",
    "  git config user.name 'OpenHands Automation'",
    "  gh auth setup-git",
    "",
    "## Step 1 - Identify the triggering PR",
    "",
    "The pull_request.labeled event includes the PR number and head branch in your conversation",
    "context. Look for the event payload to find PR_NUMBER and HEAD_BRANCH.",
    "",
    "If not visible in context, fall back to:",
    "  gh pr list --repo rajshah4/automated-qa-demo --state=open --sort=updated --direction=desc",
    "    --json number,headRefName,labels,title --limit=10",
    "    --jq '.[] | select(.labels[].name==\"openhands-qa\") | {number,headRefName,title}'",
    "",
    "Pick the most recently labeled PR. Store as PR_NUMBER and HEAD_BRANCH.",
    "",
    "## Step 2 - Checkout the PR branch and detect the scenario",
    "",
    "  git fetch origin",
    '  git checkout "$HEAD_BRANCH" 2>/dev/null || git checkout -b "$HEAD_BRANCH" "origin/$HEAD_BRANCH"',
    "",
    "Get changed files:",
    '  gh pr view "$PR_NUMBER" --repo rajshah4/automated-qa-demo --json files --jq \'.files[].path\'',
    "",
    "Detect the scenario — store result as SCENARIO variable:",
    "",
    "  1. FILE PATHS (primary): look at the changed files list:",
    "     - Any file under scenarios/03_ui_workflow/  -> SCENARIO=scenarios/03_ui_workflow  (UI QA)",
    "     - Any file under scenarios/02_api_new_generation/ -> SCENARIO=scenarios/02_api_new_generation  (API QA)",
    "     - Any file under scenarios/01_api_pr_update/ -> SCENARIO=scenarios/01_api_pr_update  (API QA)",
    "",
    "  2. BRANCH NAME (tiebreaker — only when file paths are ambiguous or point to a shared folder):",
    "     - HEAD_BRANCH contains 'ui'  -> SCENARIO=scenarios/03_ui_workflow",
    "     - HEAD_BRANCH contains '02'  -> SCENARIO=scenarios/02_api_new_generation",
    "     - HEAD_BRANCH contains '01'  -> SCENARIO=scenarios/01_api_pr_update",
    "",
    "  3. DEFAULT: SCENARIO=scenarios/01_api_pr_update",
    "",
    "NOTE: scenarios/02_api_new_generation deliberately shares the service/ code in",
    "scenarios/01_api_pr_update/. If changed files point to scenarios/01_api_pr_update/",
    "but the branch name indicates '02', use SCENARIO=scenarios/02_api_new_generation",
    "(new endpoint, no existing tests — generate from scratch).",
    "",
    "## Step 3 - Read AGENTS.md and skills",
    "",
    "  cat AGENTS.md",
    "  cat agents/api_qa_agent.py   # study _build_prompt()",
    "  cat agents/ui_qa_agent.py    # study _build_prompt()",
    "  # API scenarios: cat skills/api-qa-conventions/SKILL.md",
    "  # UI scenario:   cat skills/webapp-testing/SKILL.md && cat skills/front-end-testing/SKILL.md",
    "",
    "## Step 4 - Run the QA work",
    "",
    "First capture the start time:",
    "  QA_START=$(date +%s)",
    "",
    "Follow the EXACT task instructions in _build_prompt() of the matching agent script.",
    "YOUTUBE_API_KEY and GITHUB_TOKEN are available from the sandbox secrets store.",
    "",
    "## Step 5 - Commit artifacts back to the PR branch",
    "",
    "After tests pass, stage everything generated under the detected SCENARIO path.",
    "Do NOT hardcode scenario folder names — use the SCENARIO variable you detected in Step 2.",
    "",
    "For all scenarios — use $SCENARIO (set in Step 2), never a hardcoded path:",
    "  # Convert any .webm recordings to GIF (no-op for API scenarios which have none)",
    "  apt-get install -y ffmpeg -qq 2>/dev/null || true",
    '  GIF_COUNT=0',
    '  for webm in "$SCENARIO"/recordings/*.webm 2>/dev/null; do',
    '    [ -f "$webm" ] || continue',
    '    ffmpeg -i "$webm" -vf "fps=8,scale=900:-1" "${webm%.webm}.gif" -y -loglevel quiet && GIF_COUNT=$((GIF_COUNT+1))',
    "  done",
    '  git add "$SCENARIO/"',
    '  if [ "$GIF_COUNT" -gt 0 ]; then',
    "    COMMIT_MSG='test(qa): generated specs + preview GIFs via OpenHands Automation [skip ci]'",
    "  else",
    "    COMMIT_MSG='test(qa): automated tests via OpenHands Automation [skip ci]'",
    "  fi",
    '  git diff --cached --quiet || git commit -m "$COMMIT_MSG"',
    '  git push origin "$HEAD_BRANCH"',
    "",
    "If push fails with auth error: gh auth setup-git && git push origin \"$HEAD_BRANCH\"",
    "",
    "## Step 6 - Post the PR comment",
    "",
    "Compute duration (QA_START was captured in Step 4):",
    "  QA_END=$(date +%s)",
    "  QA_DURATION=$(( QA_END - QA_START ))",
    "  QA_DURATION_FMT=\"$(( QA_DURATION / 60 ))m $(( QA_DURATION % 60 ))s\"",
    "",
    "Get the conversation URL from the environment:",
    "  CONV_URL=$(echo \"${AGENT_SERVER_URL}\" | sed 's|/api||' 2>/dev/null || echo 'https://app.all-hands.dev')",
    "  # The conversation ID is the last path segment of AGENT_SERVER_URL or available as $CONVERSATION_ID",
    "  # Construct: https://app.all-hands.dev/conversations/<CONVERSATION_ID>",
    "",
    "Write /tmp/pr-automation-comment.md with this structure:",
    "",
    "  \U0001f916 **Automated QA (via OpenHands Automation) - `<SCENARIO>`**",
    "",
    "  | | |",
    "  |---|---|",
    "  | Status | `<pass / fail>` |",
    "  | Scenario | `<scenario path>` |",
    "  | Model | OpenHands Automation |",
    "  | Duration | `<QA_DURATION_FMT>` |",
    "  | Triggered by | `openhands-qa` label |",
    "  | Conversation | `<link to https://app.all-hands.dev/conversations/<id> if available>` |",
    "",
    "  ### QA Summary",
    "  <test counts, what changed, what was generated — key lines from /tmp/qa-report.md>",
    "",
    "  ### Full QA report",
    "  <details>",
    "  <summary>qa-report.md</summary>",
    "",
    "  ```",
    "  <full verbatim contents of /tmp/qa-report.md>",
    "  ```",
    "  </details>",
    "",
    "  ### Generated files",
    "  For each file committed in Step 5, add a collapsible block:",
    "  <details>",
    "  <summary><code>path/to/file.py</code> — <one-line description></summary>",
    "",
    "  ```python",
    "  <full file contents>",
    "  ```",
    "  </details>",
    "",
    "  For UI scenario: also embed GIFs inline (already done in Step 5 commit, reference raw GitHub URLs).",
    "",
    "  ---",
    "  _Generated by OpenHands Automation on behalf of rajshah4._",
    "",
    "Then post:",
    '  gh pr comment "$PR_NUMBER" --repo rajshah4/automated-qa-demo --body-file /tmp/pr-automation-comment.md',
    "",
    "## Hard constraints",
    "- Do NOT modify .github/workflows/qa.yml.",
    "- Do NOT open new PRs.",
    "- Only push to HEAD_BRANCH. Never push to main.",
])

payload = {
    "name": "automated-qa-demo \u2014 PR QA trigger",
    "prompt": prompt,
    "trigger": {
        "type": "event",
        "source": "github",
        "on": "pull_request.labeled",
        "filter": "repository.full_name == 'rajshah4/automated-qa-demo' && contains(pull_request.labels[].name, 'openhands-qa')"
    },
    "repos": [{"url": "https://github.com/rajshah4/automated-qa-demo", "ref": "main"}],
    "timeout": 1800
}

with open("/tmp/automation-payload.json", "w") as f:
    json.dump(payload, f, indent=2, ensure_ascii=False)
print(f"Written. Prompt: {len(prompt)} chars")
